<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH03B7Fp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH03B7Fp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH03B7Fp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH03B7Fp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH03B7Fp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H03B7Fp',
    'container.build_id' => '4796ccb2',
    'container.build_time' => 1612532356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH03B7Fp');
